{{ if .Values.hpa.enabled -}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: statemachine2
  namespace: {{ .Release.Namespace }}
  labels:
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas | default 10 }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: statemachine2
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage | default 50 }}
{{- end }}