---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: statemachine2
{{ include "charts.labels.standard" .}}
  name: statemachine2
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: "http"
    port: {{.Values.global.ports.statemachine2}}
    targetPort: "http"
  selector:
    app: statemachine2
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}