{{ if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
data:
  Brokers: {{ .Values.configmap.Brokers }}
  RequireSSL: "{{ .Values.configmap.RequireSSL }}"
{{ if .Values.configmap.TopicPrefix }}
  TopicPrefix: {{ .Values.configmap.TopicPrefix }}
{{ else }}
  TopicPrefix: "{{ .Release.Namespace }}-"
{{ end }}
  Username: {{ .Values.configmap.Username }}
  Version: {{ .Values.configmap.Version }}
{{ end }}