{{ if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
data:
  Brokers: {{ .Values.configmap.Brokers }}
  RequireSSL: "{{ .Values.configmap.RequireSSL }}"
{{ if .Values.configmap.TopicPrefix }}
  TopicPrefix: {{ .Values.configmap.TopicPrefix }}
{{ else }}
  TopicPrefix: "{{ .Release.Namespace }}-"
{{ end }}
  EmailsTopic: {{ .Values.configmap.EmailsTopic }}
  MarketoTopic: {{ .Values.configmap.MarketoTopic | default "marketo"}}
  MetricEventsTopic: {{ .Values.configmap.MetricEventsTopic | default "metric-events" }}
  MetricEventsKissMetricsDeadLettersTopic: {{ .Values.configmap.MetricEventsKissMetricsDeadLettersTopic }}
  Username: {{ .Values.configmap.Username }}
  Version: {{ .Values.configmap.Version }}
{{ end }}